# Generated by Django 4.1.5 on 2023-01-20 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divulga', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
    ]
