# Generated by Django 4.1.5 on 2023-01-20 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divulga', '0002_delete_categoria_delete_marca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='marca',
        ),
    ]
